parameters:
  stinger_soft.entity_search.doctrine.listener.class: StingerSoft\EntitySearchBundle\Services\DoctrineListener
  stinger_soft.entity_search.entity_to_document_mapper.class: StingerSoft\EntitySearchBundle\Services\Mapping\EntityToDocumentMapper
  stinger_soft.entity_search.search_service.class: StingerSoft\EntitySearchBundle\Services\DummySearchService
  stinger_soft.entity_search.document_to_entity_mapper.class: StingerSoft\EntitySearchBundle\Services\Mapping\DocumentToEntityMapper
  stinger_soft.entity_search.forms.query_type.class: StingerSoft\EntitySearchBundle\Form\QueryType

  stinger_soft_entity_search.facets.author.class: 'StingerSoft\EntitySearchBundle\Services\Facet\AuthorFacet'
  stinger_soft_entity_search.facets.editors.class: 'StingerSoft\EntitySearchBundle\Services\Facet\EditorsFacet'
  stinger_soft_entity_search.facets.type.class: 'StingerSoft\EntitySearchBundle\Services\Facet\TypeFacet'
  stinger_soft_entity_search.facets.filetype.class: 'StingerSoft\EntitySearchBundle\Services\Facet\FileTypeFacet'

services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  stinger_soft.entity_search.dummy_search_service:
    class: '%stinger_soft.entity_search.search_service.class%'
    
  StingerSoft\EntitySearchBundle\Services\DoctrineListener:
    class: '%stinger_soft.entity_search.doctrine.listener.class%'
    tags:
        - { name: doctrine.event_subscriber }

  StingerSoft\EntitySearchBundle\Services\Mapping\EntityToDocumentMapperInterface:
    class: '%stinger_soft.entity_search.entity_to_document_mapper.class%'

  StingerSoft\EntitySearchBundle\Services\Mapping\DocumentToEntityMapperInterface:
    class: '%stinger_soft.entity_search.document_to_entity_mapper.class%'

  stinger_soft.entity_search.forms.query_type:
    class: "%stinger_soft.entity_search.forms.query_type.class%"
    tags:
      - { name: form.type }

  stinger_soft_entity_search.facets.author:
    class: "%stinger_soft_entity_search.facets.author.class%"

  stinger_soft_entity_search.facets.editors:
      class: "%stinger_soft_entity_search.facets.editors.class%"

  stinger_soft_entity_search.facets.type:
      class: "%stinger_soft_entity_search.facets.type.class%"

  stinger_soft_entity_search.facets.filetype:
      class: "%stinger_soft_entity_search.facets.filetype.class%"