parameters:
  stinger_soft.entity_search.doctrine_update_listener.class: StingerSoft\EntitySearchBundle\Services\DoctrineListener
  stinger_soft.entity_search.search_service.class: StingerSoft\EntitySearchBundle\Services\DummySearchService
  
services:
  stinger_soft.entity_search.doctrine_update_listener:
    class: %stinger_soft.entity_search.search_service.class%
    
    
  pec_search.doctrine.listener:
    arguments: ["@stinger_soft.entity_search.doctrine_update_listener"]
    class: %stinger_soft.entity_search.doctrine_update_listener.class%
      tags:
        - { name: doctrine.event_listener, event: postPersist }
        - { name: doctrine.event_listener, event: preRemove }
        - { name: doctrine.event_listener, event: postUpdate }
#        calls:
#          - [ setContainer,[ "@service_container" ] ]