parameters:
  stinger_soft.entity_search.doctrine_update_listener.class: StingerSoft\EntitySearchBundle\Services\DoctrineListener
  stinger_soft.entity_search.search_service.class: StingerSoft\EntitySearchBundle\Services\DummySearchService
  
services:
  stinger_soft.entity_search.doctrine_update_listener:
    class: '%stinger_soft.entity_search.search_service.class%'
    
    
  stinger_soft.entity_search.doctrine.listener:
    arguments: ["@stinger_soft.entity_search.doctrine_update_listener"]
    class: '%stinger_soft.entity_search.doctrine_update_listener.class%'
    tags:
        - { name: doctrine.event_subscriber }