parameters:
  stinger_soft.entity_search.doctrine.listener.class: StingerSoft\EntitySearchBundle\Services\DoctrineListener
  stinger_soft.entity_search.entity_to_document_mapper.class: StingerSoft\EntitySearchBundle\Services\Mapping\EntityToDocumentMapper
  stinger_soft.entity_search.search_service.class: StingerSoft\EntitySearchBundle\Services\DummySearchService
  stinger_soft.entity_search.document_to_entity_mapper.class: StingerSoft\EntitySearchBundle\Services\Mapping\DocumentToEntityMapper
  
services:
  stinger_soft.entity_search.search_service:
    class: '%stinger_soft.entity_search.search_service.class%'
    
    
  stinger_soft.entity_search.doctrine.listener:
    arguments: ["@stinger_soft.entity_search.entity_to_document_mapper", "@stinger_soft.entity_search.search_service"]
    class: '%stinger_soft.entity_search.doctrine.listener.class%'
    tags:
        - { name: doctrine.event_subscriber }
        
  stinger_soft.entity_search.entity_to_document_mapper:
    arguments: ["@stinger_soft.entity_search.search_service"]
    class: '%stinger_soft.entity_search.entity_to_document_mapper.class%'
  
  stinger_soft.entity_search.document_to_entity_mapper:
    class: '%stinger_soft.entity_search.document_to_entity_mapper.class%'
    arguments: ["@doctrine"]
